AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an ECR Repo
Parameters:
  RepositoryName:
    Type: String
    Description: A name for the service
  ContainerName:
    Type: String
    Description: Name of the container
  ParameterName:
    Type: String
    Description: Paramater name for version
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryPolicyText:
        Version: "2008-10-17"
        Statement:
          - Sid: Allow Push
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::076279718063:user/codyp
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', [!Ref ContainerName, 'Role']]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /cluster/
      Policies:
        - PolicyName: !Join ['-', [!Ref ContainerName, 'Policy']]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: arn:aws:s3:::static.thevoyapp.com/*
              - Effect: Allow
                Action:
                  - apigateway:get
                Resource: arn:aws:apigateway:us-east-2::/apikeys/*
              - Effect: Allow
                Action: ssm:GetParameter
                Resource: !Join
                  - ""
                  - - "arn:aws:ssm:"
                    - !Ref AWS::Region
                    - ":"
                    - !Ref AWS::AccountId
                    - ":parameter"
                    - !Ref ParameterName
                    - "*"
